FROM registry.cn-hangzhou.aliyuncs.com/kendryte/nncase:latest

RUN apt update
RUN apt install -y curl
RUN apt install -y xz-utils

ENV NNCASE_VERSION 0.2.0
ENV NNCASE_BUILD beta4
ENV NNCASE_PACKAGE ncc_linux_x86_64.tar.xz

WORKDIR /root
RUN curl -LO https://github.com/kendryte/nncase/releases/download/v$NNCASE_VERSION-$NNCASE_BUILD/$NNCASE_PACKAGE
RUN tar Jxfv $NNCASE_PACKAGE
RUN mv ncc /usr/local/bin
RUN rm $NNCASE_PACKAGE

WORKDIR /root
